print(i see)
print(door 4)
print(throw ball)
print(you are there)
print(where are you)
print(i got you)
print(i agree)
print(look at him)
print(saba shelia)
print(this car is mine)
print(my brother has his own business)
print(fqeqefwef eqgq)
print(windows 7)
print(windows 8)
print(windows 10)
print(windows 11)
print(i have dog)
print(i love her)
print(family is important for me)

